export const SET_INSTAGRAM_ACCESS_TOKEN = 'SET_INSTAGRAM_ACCESS_TOKEN';
export const SET_INSTAGRAM_USER = 'SET_INSTAGRAM_USER';
export const SET_INSTAGRAM_MEDIA = 'SET_INSTAGRAM_MEDIA';
export const SET_FACEBOOK_ACCESS_TOKEN = 'SET_FACEBOOK_ACCESS_TOKEN';
export const SET_FACEBOOK_USER = 'SET_FACEBOOK_USER';
export const SET_FACEBOOK_MEDIA = 'SET_FACEBOOK_MEDIA';
export const SET_CURRENT_VIEW = 'SET_CURRENT_VIEW';
